### ISSUE TITLE
Feature Request: Intercom Destination

### ISSUE THREAD

**Issue by andyjih** [grouparoo/grouparoo#1046]

**Comment by bleonard** [comment]
Intercom has [Contacts](https://developers.intercom.com/intercom-api-reference/reference#contacts-model), [Companies](https://developers.intercom.com/intercom-api-reference/reference#company-model), [Tags](https://developers.intercom.com/intercom-api-reference/reference#tag-model), [Segments](https://developers.intercom.com/intercom-api-reference/reference#segment-model), 

You don’t seem to be able to create Segments via the API. They are only dynamic and created in the UI via the filtering mechanism.

Tags can be used as a way to create Filters (and therefore Segments)

**App**

Looks like it has an app id and api key.

**Profiles**

There are two concepts. Leads and Users. Both are Contacts.

There are also [Visitors](https://developers.intercom.com/intercom-api-reference/reference#visitor-object), who are anonymous. That’s a different API though.

A lead becomes as user when they have signed up, though you might have that info ahead of time. It feels like Salesforce.

There is a “role” attribute that says which they are.

Maybe that means there should be two destinations?

Another option would be to always make Users, but make them leads if they don’t have external id or email. Not sure. It feels a bit better not to be working on them separately.

Maybe there is an option for Lead, Contact, or Combo.

There is no bulk API that I can see.

[Search](https://developers.intercom.com/intercom-api-reference/reference#search-for-contacts): POST to [https://api.intercom.io/contacts/search](https://api.intercom.io/contacts/search)

This looks pretty flexible.

[Create](https://developers.intercom.com/intercom-api-reference/reference#create-contact)

Required fields:

Role: contact or lead

External_id: Yes - if role is user and email is blank

Email: Yes - if role is user and external_id is blank

[Update](https://developers.intercom.com/intercom-api-reference/reference#update-contact)

Update based on the destinationId

Same required fields as above

Can update the role from a lead to a user, but not in the other direction

[Merge](https://developers.intercom.com/intercom-api-reference/reference#merge-contact): can combine a lead into a user.

Maybe this case exists if it turns out later they had different email addresses, but now we know they are the same external_id?

**Deleting**

There are two things here: [Delete](https://developers.intercom.com/intercom-api-reference/reference#delete-contact) and [Archive](https://developers.intercom.com/intercom-api-reference/reference#archive-a-contact).

I’m thinking we should probably archive. It’s yet to be seen if those show up in search or if I can can create a “duplicate”.

**Properties**

There are many [built in fields](https://developers.intercom.com/intercom-api-reference/reference#contacts-model). You can also add custom_attributes.

You can only write to custom data attributes that already exist on the workspace. 

[Fields](https://developers.intercom.com/intercom-api-reference/reference#data-attribute-model): GET [https://api.intercom.io/data_attributes?model=contact](https://api.intercom.io/data_attributes?model=contact) 

Types: string, integer, float, boolean, date (epoch time, so actually a datetime). They treat dates (2020-12-22) as epoch time at the beginning of UTC.

**Groups**

Tags seem like the best path forward, but it’s going to be a lot of API calls.

Ther other option would be boolean properties. Grouparoo Core isn’t set up to do that, yet though. This would be much more efficient. Then there wouldn’t be any use of Groups though. So let’s start by adding tag support and when we add the group boolean mapping, they can choose to use that.

[What tags](https://developers.intercom.com/intercom-api-reference/reference#list-tags-of-contact) use a contact current have?

[List all tags](https://developers.intercom.com/intercom-api-reference/reference#list-tags-for-an-app)

[Create a tag](https://developers.intercom.com/intercom-api-reference/reference#create-and-update-tags)

[Tag a contact](https://developers.intercom.com/intercom-api-reference/reference#tag-contact) with one tag

**Other**

Rate Limit : Responds with 429 state code 

X-RateLimit-Limit: Maximum number of requests allowed for the app.

X-RateLimit-Remaining: Number of requests left in the current time.

X-RateLimit-Reset: Time when the number of requests will be reset to the maximum limit.

Overall, there looks to be a decent lag in the UI and the documentation. For example a user might not be in search right after creation.

Other Connections



*   [Segment](https://segment.com/docs/connections/destinations/catalog/intercom/): “users” and create user-level custom attributes for groups (allowing creation of segments in UI). Does not support “leads”

**Comment by bleonard** [comment]
Add a destination in this PR: https://github.com/grouparoo/grouparoo/pull/1145

Choices for creation:
* User
* Lead
* Lifecycle: Lead if there is no external_id, otherwise User
* Enrich: no creation

Choices for removal:
* Archive
* Delete permanently
* No removal
