### ISSUE TITLE
Feature Request: Customer.io Destination

### ISSUE THREAD

**Issue by andyjih** [grouparoo/grouparoo#1149]
Add Customer.io as a destination for Grouparoo profiles and groups.

**Comment by bleonard** [comment]
**<span style="text-decoration:underline;">Profiles</span>**

The core object is a Customer. 

PUT /customers/:id
https://customer.io/docs/api/#operation/identify

The :id in this case seems to be anything string you want and should be an “external id” like in other systems.

It takes in attributes. There is a limit of 300 unique attributes set per call. 

```
cio.identify(5, {
  email: 'customer@example.com',
  created_at: 1361205308,
  first_name: "Bob",
  plan: "basic"
});
```

There is no `GET` request that I can find given the id.

It has dynamic properties so `allowOptionalFromProperties` will be `true` on `destinationMappingOptions` (like sailthru, for example).

**<span style="text-decoration:underline;">Properties</span>**

There is no obvious way that I can see to get all the properties that currently exist, but there are a few well known properties.

Required: customer_id
Known: email, created_at (date)
The rest will be set to whatever type Grouparoo has them, but each needs to be mapped to a string, integer, or boolean values.

For formatVar:
Null/undefined: null
Date: Math.round(obj.getTime() / 1000)
Float: Math.round(obj)
Integer: fine as is
Boolean: fine as is
Otherwise: obj.toString()

It says: To remove an attribute on an existing customer, set its value to an empty string.
But we should experiment with null to be clearer and see if that works. it's weird to send a string to a integer column.

**<span style="text-decoration:underline;">Delete</span>**

You can delete to the same endpoint to remove the user.

DELETE /customers/:id

It looks like we’ll have to do this is they change their external id as well, similar to how sendgrid works. Delta the old one and add the new one.

**<span style="text-decoration:underline;">Groups</span>**

It is not recommended to create Segments. Other service like [mParticle](https://customer.io/docs/integrating-with-mparticle), do this based on a setting:

If enabled, mParticle will forward membership information for each segment as a seperate user attribute. For example, if you’re forwarding a segment named “New Users” mParticle will forward membership information for this segment in a user attribute called “In New Users, with a value of “true” or “false”. If disabled, mParticle will forward a single user attribute called “Segment Membership”, and it’s value will be a comma-separated list of mParticle segment IDs that the user is a member of, wrapped in single quotes. If you’re unsure what to select here we recommend enabling this feature.


Let’s just do the properties first, so we would have 
`payload[`In ${groupName}`] = true`
We should check if setting to false, null, or empty string removes them . It’s better to remove the property so we clean up after ourselves.

The user can use this to make dynamic segments in customer.io

**<span style="text-decoration:underline;">Summary</span>**

So in the end, there is usually only one API call per profile.

1. Require customer_id
2. If changed customer_id, send delete to old one (ok if not found)
3. If deleting, send delete for customer_id (ok if not found) and return
4. Build payload, formatting each var
5. Add group to payload for all new/old Groups using payload[`In ${groupName}`] approach
6. Make identify call with payload
