### ISSUE TITLE
When associating events to profiles, check profile#annonId AND all events for that profile which many have had other annonIDs

### ISSUE THREAD

**Issue by evantahler** [grouparoo/grouparoo#221]
around here 

```
      if (!profile) {
        [profile] = await Profile.findOrCreate({
          where: { anonymousId: this.anonymousId },
        });
      }

```

**Comment by andyjih** [comment]
I created events with an anonymous ID already associated with a profile. Should we expect the API response to return the profile ID? I was thinking we would since we know that this anonymous ID is tied to this profile, but let me know if you had something else in mind. 

![Screen Shot 2020-06-11 at 3 40 07 PM](https://user-images.githubusercontent.com/633226/84446292-0575c780-abfa-11ea-8e12-1b66c30b1e51.png)

**Comment by evantahler** [comment]
No... we don't do the association to the profile as part of the request to create the profile (it can be slow).  We do that later in a background task.  

The response you get back from the API shows the (newly created) event's information at that moment. If you wait a few seconds and then GET that same event's guid, the `profileGuid` should be set then.

**Comment by evantahler** [comment]
The hint in the API response that the profile hasn't been associated yet is `associatedAt=null`
